package cxf.stub;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.0
 * 2015-12-30T15:57:35.746+08:00
 * Generated source version: 2.7.0
 * 
 */
@WebService(targetNamespace = "http://test.com/", name = "HelloWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface HelloWebService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "say", targetNamespace = "http://test.com/", className = "cxf.stub.Say")
    @WebMethod
    @ResponseWrapper(localName = "sayResponse", targetNamespace = "http://test.com/", className = "cxf.stub.SayResponse")
    public java.lang.String say(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
